# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c092e5a8c53d9712a03716b7ed29d460891058ed20855dd1be11583725074b14f6856c1ce64d8976c1d95bbdf330ab40e73cfd7a9d80bd08f67efe55be287dcf

test:
  secret_key_base: e22f78923ca0c9b73eb0288922c28a5c09bb7c68ce8627a716b5a9823240fd98754c07b1d1087045f69a27840454a7152b48c07616ff10ade4a61ee8a60678d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
